name: Deploy to Production

on:
  release:
    types: [published]

jobs:
  deploy-frontend-production:
    name: Deploy Frontend to Vercel Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install Vercel CLI
        run: pnpm install -g vercel@48.6.0

      - name: Get Current Staging Deployment
        id: get_staging
        working-directory: frontend
        run: |
          STAGING_URL=$(vercel alias ls --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }} | grep "${{ secrets.VERCEL_STAGING_ALIAS }}" | awk '{print $2}')
          echo "url=$STAGING_URL" >> $GITHUB_OUTPUT
          echo "Promoting from staging: $STAGING_URL"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Promote Staging to Production
        working-directory: frontend
        run: |
          vercel promote ${{ steps.get_staging.outputs.url }} --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }} --yes
          echo "Production deployment complete!"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  deploy-backend-production:
    name: Deploy Backend to Railway Production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway Production
        run: railway up --service=${{ secrets.RAILWAY_SERVICE_NAME }} --environment=production --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
